apiVersion: v1
kind: ConfigMap
metadata:
  name: cardiollm-config
  namespace: cardiollm
data:
  SESSION_HOURS: "8"
  COOKIE_SECURE: "true"
  KEEP_ALIVE: "30m"
  OLLAMA_BASE_URL: "http://replace-with-ollama-host:11434"
  OLLAMA_TRANS_MODEL: "replace-with-your-translator-model:q8"
  OLLAMA_SUM_MODEL: "replace-with-your-summarizer-model:q8"
